[build-system]
build-backend = "maturin"
requires = [ "maturin>=1,<2" ]

[project]
name = "kreuzberg"
version = "4.0.0"
description = "High-performance document intelligence library for Python. Extract text, metadata, and structured data from PDFs, Office documents, images, and 50+ formats. Powered by Rust core for 10-50x speed improvements."
readme = "README.md"
keywords = [
  "document-extraction",
  "document-intelligence",
  "document-parsing",
  "document-processing",
  "docx",
  "easyocr",
  "email-parsing",
  "html",
  "markdown",
  "metadata-extraction",
  "ocr",
  "office-documents",
  "paddleocr",
  "pdf",
  "pdf-extraction",
  "performance",
  "pptx",
  "rust",
  "table-extraction",
  "tesseract",
  "text-extraction",
  "xlsx",
  "xml",
]
license = { text = "MIT" }
maintainers = [ { name = "Na'aman Hirschfeld", email = "nhirschfeld@gmail.com" } ]
authors = [ { name = "Na'aman Hirschfeld", email = "nhirschfeld@gmail.com" } ]
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Rust",
  "Topic :: Office/Business",
  "Topic :: Scientific/Engineering :: Information Analysis",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Text Processing",
  "Topic :: Text Processing :: Filters",
  "Topic :: Text Processing :: General",
  "Typing :: Typed",
]

dependencies = [  ]

optional-dependencies.all = [
  "kreuzberg[easyocr,paddleocr]",
]
optional-dependencies.easyocr = [
  "easyocr>=1.7.2; python_version<'3.14'",
  "torch>=2.9; python_version<'3.14'",
]
optional-dependencies.paddleocr = [
  "paddleocr>=3.3; python_version<'3.14'",
  "paddlepaddle>=3.2; python_version<'3.14'",
  "setuptools>=80.9; python_version<'3.14'",
]
urls.Changelog = "https://kreuzberg.dev/CHANGELOG/"
urls.Documentation = "https://kreuzberg.dev"
urls.Homepage = "https://kreuzberg.dev"
urls.Issues = "https://github.com/Goldziher/kreuzberg/issues"
urls.Repository = "https://github.com/Goldziher/kreuzberg"
urls.Source = "https://github.com/Goldziher/kreuzberg"
scripts.kreuzberg = "kreuzberg.__main__:main"

[tool.maturin]
module-name = "kreuzberg._internal_bindings"
# Point to the PyO3 bindings crate
manifest-path = "../../crates/kreuzberg-py/Cargo.toml"
# Build the CLI binary from the workspace and include it
bins = [
  { name = "kreuzberg", package = "kreuzberg-cli", rename-to = "kreuzberg-cli", features = [ "all" ] },
]
# Include pdfium.dll on Windows (if present)
include = [
  { path = "kreuzberg/pdfium.dll", format = "wheel" },
]
