repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-case-conflict
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.11.0
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.3.2 # Use the sha / tag you want to point at
    hooks:
      - id: biome-check
  - repo: https://github.com/oxc-project/mirrors-oxlint
    rev: v1.24.0
    hooks:
      - id: oxlint
        args: ["--fix"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: [ "--fix", "--unsafe-fixes" ]
      - id: ruff-format
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
  - repo: https://github.com/rubocop/rubocop
    rev: v1.69.2
    hooks:
      - id: rubocop
        args: ['--autocorrect', '--config', 'packages/ruby/.rubocop.yml']
        files: ^packages/ruby/
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        require_serial: true
        language: system
        types: [ python ]
        exclude: ^scripts/|^comparative-benchmarks/|^examples/
