site_name: Kreuzberg
site_description: A modern text extraction library supporting PDFs, images, office documents and more
site_url: https://kreuzberg.dev
site_author: Kreuzberg Contributors
repo_name: Goldziher/kreuzberg
repo_url: https://github.com/Goldziher/kreuzberg
edit_uri: edit/main/docs/
copyright: |
  Copyright &copy; 2023-2025 Kreuzberg Contributors<br>
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
    - announce.dismiss
  icon:
    repo: fontawesome/brands/github
  language: en

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: ["."]
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search
  # TODO: Add Algolia DocSearch for enhanced search
  # Requires manual setup with Algolia DocSearch (https://docsearch.algolia.com/)
  # Configuration format:
  # - search:
  #     lang: en
  # Then add to extra section:
  # extra:
  #   search:
  #     provider: algolia
  #     api_key: YOUR_API_KEY
  #     index_name: YOUR_INDEX_NAME
  # - social  # Disabled: requires cairo library
  - tags
  - minify:
      minify_html: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [packages/python]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2
            show_category_heading: true
            show_if_no_docstring: false
            show_signature_annotations: true
            show_submodules: false
            docstring_style: google
            docstring_section_style: spacy
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
      enable_creation_date: true
      enabled: true

extra:
  # Announcement bar - uncomment and customize when needed
  # announcement:
  #   content: |
  #     <strong>🎉 Kreuzberg v4.0 is now available!</strong> Check out the <a href="/migration/v3-to-v4">migration guide</a>.
  #   dismiss: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Goldziher/kreuzberg
      name: View on GitHub
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/kreuzberg/
      name: View on PyPI
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/goldziher/kreuzberg
      name: View on Docker Hub
    - icon: fontawesome/brands/npm
      link: https://www.npmjs.com/package/kreuzberg
      name: View on npm
    - icon: fontawesome/brands/rust
      link: https://crates.io/crates/kreuzberg
      name: View on crates.io
  version:
    provider: mike
    default: latest
  analytics:
    provider: google
    property: !ENV [GOOGLE_ANALYTICS_KEY, ""]
  status:
    new: Recently added
    deprecated: Deprecated
  repo:
    stars: true
    forks: true

extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - Installation: getting-started/installation.md
  - Quick Start: getting-started/quickstart.md
  - Features: features.md
  - Concepts:
      - Architecture: concepts/architecture.md
      - Extraction Pipeline: concepts/extraction-pipeline.md
      - Plugin System: concepts/plugin-system.md
      - MIME Detection: concepts/mime-detection.md
      - Performance: concepts/performance.md
  - Guides:
      - Extraction Basics: guides/extraction.md
      - Configuration: guides/configuration.md
      - OCR: guides/ocr.md
      - Advanced Features: guides/advanced.md
      - Creating Plugins: guides/plugins.md
  - CLI: cli/usage.md
  - API Server: guides/api-server.md
  - API Reference:
      - Python: reference/api-python.md
      - TypeScript: reference/api-typescript.md
      - Rust: reference/api-rust.md
      - Ruby: reference/api-ruby.md
      - Configuration: reference/configuration.md
      - Format Support: reference/formats.md
      - Types: reference/types.md
      - Errors: reference/errors.md
  - Migration Guide: migration/v3-to-v4.md
  - Changelog: changelog.md
  - Contributing: contributing.md
