name: Install System Dependencies
description: Install platform specific dependencies required for document conversion
runs:
  using: composite
  steps:
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        set -eo pipefail
        echo "Updating Homebrew..."
        brew update || true
        echo "Installing pandoc..."
        brew install pandoc || brew upgrade pandoc || true
        echo "Installing LibreOffice via Homebrew Cask..."
        brew install --cask libreoffice || brew upgrade --cask libreoffice || true
        echo "Installed packages:"
        brew list pandoc
        echo "Verifying LibreOffice installation..."
        if ! soffice --version; then
          echo "Warning: soffice not available in PATH" >&2
        fi

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -eo pipefail
        sudo apt-get update
        sudo apt-get install -y \
          pandoc \
          libreoffice
        echo "Verifying Linux installations..."
        pandoc --version
        soffice --version

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop"
        choco install -y pandoc libreoffice --no-progress
        Write-Output "C:\Program Files\Pandoc" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        Write-Output "C:\Program Files\LibreOffice\program" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        $env:PATH = "C:\Program Files\Pandoc;C:\Program Files\LibreOffice\program;" + $env:PATH

        # Install python-magic-bin for Windows compatibility
        python -m pip install python-magic-bin

        pandoc --version
        soffice --version
