# frozen_string_literal: true

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'lib/**/*.bundle'
    - 'ext/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/Documentation:
  Enabled: false # We use YARD for documentation

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\A\s*#' # Allow long comment lines

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - 'Rakefile'

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/ParameterLists:
  Max: 7

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false
