from typing import Any

class CacheStats:
    total_files: int
    total_size_mb: float
    available_space_mb: float
    oldest_file_age_days: float
    newest_file_age_days: float

def generate_cache_key(**kwargs: Any) -> str: ...
def batch_generate_cache_keys(items: list[Any]) -> list[str]: ...
def fast_hash(data: bytes) -> int: ...
def validate_cache_key(key: str) -> bool: ...
def filter_old_cache_entries(cache_times: list[float], current_time: float, max_age_seconds: float) -> list[int]: ...
def sort_cache_by_access_time(entries: list[tuple[str, float]]) -> list[str]: ...
def get_available_disk_space(path: str) -> float: ...
def get_cache_metadata(cache_dir: str) -> CacheStats: ...
def cleanup_cache(
    cache_dir: str, max_age_days: float, max_size_mb: float, target_size_ratio: float
) -> tuple[int, float]: ...
def smart_cleanup_cache(
    cache_dir: str, max_age_days: float, max_size_mb: float, min_free_space_mb: float
) -> tuple[int, float]: ...
def is_cache_valid(cache_path: str, max_age_days: float) -> bool: ...
def clear_cache_directory(cache_dir: str) -> tuple[int, float]: ...
def batch_cleanup_caches(
    cache_dirs: list[str], max_age_days: float, max_size_mb: float, min_free_space_mb: float
) -> list[tuple[int, float]]: ...
def calculate_quality_score(text: str, ocr_confidence: float | None, has_tables: bool, has_images: bool) -> float: ...
def clean_extracted_text(text: str) -> str: ...
def normalize_spaces(text: str) -> str: ...
def safe_decode(data: bytes) -> str: ...
def batch_process_texts(texts: list[bytes]) -> list[str]: ...
def calculate_text_confidence(text: str) -> float: ...
def fix_mojibake(text: str) -> str: ...
def get_encoding_cache_key(data: bytes) -> str: ...
def normalize_image_dpi(
    image_array: Any, config: ExtractionConfig, dpi_info: dict[str, float] | None = None
) -> tuple[Any, ImagePreprocessingMetadata]: ...
def batch_normalize_images(
    images: list[Any], config: ExtractionConfig
) -> list[tuple[Any, ImagePreprocessingMetadata]]: ...
def calculate_optimal_dpi(
    page_width: float, page_height: float, target_dpi: int, max_dimension: int, min_dpi: int = 72, max_dpi: int = 600
) -> int: ...

# Image I/O functions
def load_image(data: bytes) -> tuple[bytes, int, int, str]: ...
def save_image(data: bytes, width: int, height: int, format: str) -> bytes: ...  # noqa: A002
def detect_image_format(data: bytes) -> str: ...
def load_image_as_numpy(data: bytes) -> Any: ...
def save_numpy_as_image(array: Any, format: str) -> bytes: ...  # noqa: A002

# Image compression functions
def compress_image_jpeg(data: bytes, width: int, height: int, quality: int = 85) -> bytes: ...
def compress_image_png(data: bytes, width: int, height: int, compression: int = 6) -> bytes: ...
def compress_image_auto(
    data: bytes, width: int, height: int, target_size_kb: int | None = None
) -> tuple[bytes, str]: ...

# Image format conversion functions
def rgb_to_grayscale(rgb_array: Any) -> Any: ...
def rgb_to_rgba(rgb_array: Any, alpha: int = 255) -> Any: ...
def rgba_to_rgb(rgba_array: Any) -> Any: ...
def convert_format(array: Any, to_format: str) -> Any: ...
def reduce_tokens(text: str, reduction_level: str) -> str: ...
def batch_reduce_tokens(texts: list[str], reduction_level: str) -> list[str]: ...
def get_reduction_statistics(original: str, reduced: str) -> dict[str, Any]: ...
def table_from_arrow_to_markdown(arrow_bytes: bytes) -> str: ...

# Excel processing functions
def read_excel_file(file_path: str) -> ExcelWorkbook: ...
def read_excel_bytes(data: bytes, file_extension: str) -> ExcelWorkbook: ...
def excel_to_markdown(file_path: str) -> str: ...
def benchmark_excel_reading(file_path: str, iterations: int) -> float: ...

class ImagePreprocessingMetadata:
    original_dimensions: tuple[int, int]
    original_dpi: tuple[float, float]
    target_dpi: int
    scale_factor: float
    auto_adjusted: bool
    final_dpi: int
    new_dimensions: tuple[int, int] | None
    resample_method: str
    dimension_clamped: bool
    calculated_dpi: int | None
    skipped_resize: bool
    resize_error: str | None

class ExtractionConfig:
    target_dpi: int
    max_image_dimension: int
    auto_adjust_dpi: bool
    min_dpi: int
    max_dpi: int

    def __init__(
        self,
        target_dpi: int,
        max_image_dimension: int,
        auto_adjust_dpi: bool,
        min_dpi: int,
        max_dpi: int,
    ) -> None: ...

class TokenReductionConfig: ...
class ReductionLevel: ...

class ExcelWorkbook:
    sheets: list[ExcelSheet]
    metadata: dict[str, str]

class ExcelSheet:
    name: str
    markdown: str
    row_count: int
    col_count: int
    cell_count: int
