from typing import Protocol

class TextSplitter(Protocol):
    def __init__(self, max_characters: int, overlap_characters: int) -> None: ...
    def chunks(self, text: str) -> list[str]: ...

class MarkdownSplitter(TextSplitter):
    def __init__(self, max_characters: int, overlap_characters: int) -> None: ...
    def chunks(self, text: str) -> list[str]: ...
