name: Cleanup Rust Cache
description: Remove large build artifacts to reduce cache size before saving
runs:
  using: composite
  steps:
    - name: Cleanup build artifacts
      shell: bash
      run: |
        echo "Cleaning up large build artifacts to reduce cache size..."
        # Remove Pdfium binaries from target (already cached separately)
        rm -rf target/*/build/kreuzberg-*/out/pdfium 2>/dev/null || true
        # Remove large build artifacts we don't need to cache (>10MB)
        find target -type f -name "*.rlib" -size +10M -delete 2>/dev/null || true
        find target -type f -name "*.so" -size +10M -delete 2>/dev/null || true
        find target -type f -name "*.dylib" -size +10M -delete 2>/dev/null || true
        find target -type f -name "*.dll" -size +10M -delete 2>/dev/null || true
        # Remove incremental compilation artifacts (not needed for CI caching)
        rm -rf target/*/incremental 2>/dev/null || true
        echo "Cleanup completed successfully"
        # Show remaining target size
        du -sh target 2>/dev/null || echo "No target directory found"
