name: CI Minimal

on:
  push:
    branches:
      - v4-dev
  pull_request:
    branches:
      - v4-dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Setup Rust Toolchain for Build
        uses: dtolnay/rust-toolchain@stable

      - name: Echo
        run: echo "CI Minimal successful"
