name: CI Minimal

on:
  push:
    branches:
      - v4-dev
  pull_request:
    branches:
      - v4-dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Echo
        run: echo "CI Minimal successful"
