name: Ruby CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/ruby/**'
      - 'crates/kreuzberg-rb/**'
      - 'crates/kreuzberg/**'
      - '.github/workflows/ci-ruby.yml'
      - '.github/actions/setup-rust/**'
      - '.github/actions/cache-pdfium/**'
      - '.github/actions/install-system-deps/**'
  push:
    branches:
      - main
    paths:
      - 'packages/ruby/**'
      - 'crates/kreuzberg-rb/**'
      - 'crates/kreuzberg/**'
      - '.github/workflows/ci-ruby.yml'
      - '.github/actions/setup-rust/**'
      - '.github/actions/cache-pdfium/**'
      - '.github/actions/install-system-deps/**'

concurrency:
  group: ruby-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PDFIUM_VERSION: "7455"

jobs:
  test:
    name: Test (Ruby ${{ matrix.ruby-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby-version: ['3.3', '3.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: false

      - name: Setup MSYS2 (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-gcc

      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-rust
        with:
          cache-key-prefix: ruby-${{ matrix.os }}-${{ matrix.ruby-version }}

      - name: Cache Pdfium binaries
        uses: ./.github/actions/cache-pdfium
        with:
          pdfium-version: ${{ env.PDFIUM_VERSION }}

      - name: Install system dependencies
        uses: ./.github/actions/install-system-deps

      - name: Download Pdfium binaries
        shell: bash
        run: |
          set -euo pipefail
          platform="$(uname -s)"
          case "$platform" in
            Linux*) platform_id="linux" ;;
            Darwin*) platform_id="mac" ;;
            MINGW*|MSYS*|CYGWIN*) platform_id="win" ;;
            *) echo "Unsupported platform: $platform" >&2; exit 1 ;;
          esac
          arch="$(uname -m)"
          case "$arch" in
            x86_64|amd64) arch_id="x64" ;;
            arm64|aarch64) arch_id="arm64" ;;
            *) echo "Unsupported architecture: $arch" >&2; exit 1 ;;
          esac
          version="${PDFIUM_VERSION:-7455}"
          tmpdir="$(mktemp -d)"
          curl -fsSL -o "$tmpdir/pdfium.tgz" "https://github.com/bblanchon/pdfium-binaries/releases/download/chromium/${version}/pdfium-${platform_id}-${arch_id}.tgz"
          mkdir -p "$tmpdir/extracted"
          tar -xzf "$tmpdir/pdfium.tgz" -C "$tmpdir/extracted"
          dest="$RUNNER_TEMP/pdfium"
          rm -rf "$dest"
          mv "$tmpdir/extracted" "$dest"
          rm -rf "$tmpdir"

      - name: Stage Pdfium runtime artifacts
        shell: bash
        run: |
          set -euo pipefail
          # Copy pdfium library to crates/kreuzberg-rb for linking during build
          # and to packages/ruby for runtime loading
          case "${RUNNER_OS:-unknown}" in
            Windows)
              src="$RUNNER_TEMP/pdfium/bin/pdfium.dll"
              cp -f "$src" "crates/kreuzberg-rb/pdfium.dll"
              cp -f "$src" "packages/ruby/pdfium.dll"
              ;;
            macOS)
              src="$RUNNER_TEMP/pdfium/lib/libpdfium.dylib"
              cp -f "$src" "crates/kreuzberg-rb/libpdfium.dylib"
              cp -f "$src" "packages/ruby/libpdfium.dylib"
              ;;
            Linux)
              src="$RUNNER_TEMP/pdfium/lib/libpdfium.so"
              cp -f "$src" "crates/kreuzberg-rb/libpdfium.so"
              cp -f "$src" "packages/ruby/libpdfium.so"
              ;;
            *)
              echo "Unsupported RUNNER_OS: ${RUNNER_OS:-unknown}" >&2
              exit 1
              ;;
          esac

      - name: Install Ruby dependencies
        working-directory: packages/ruby
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: Build Ruby native extension
        working-directory: packages/ruby
        run: bundle exec rake compile

      - name: Run tests
        working-directory: packages/ruby
        run: bundle exec rspec --format documentation
