name: Validate

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**'
  push:
    branches:
      - main

concurrency:
  group: validate-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PDFIUM_VERSION: "7455"

jobs:
  prek:
    name: Pre-commit hooks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: '3.13'

      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-rust
        with:
          cache-key-prefix: lint

      - name: Cache Pdfium binaries
        uses: ./.github/actions/cache-pdfium
        with:
          pdfium-version: ${{ env.PDFIUM_VERSION }}

      - name: Run Prek linters
        run: uv run prek run --show-diff-on-failure --color=always --all-files
