name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  rust-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Run Rust Tests
        env:
          RUST_BACKTRACE: full
        run: |
          echo "Running Rust tests with full debugging..."
          cargo test --release --no-default-features -vv -- --nocapture --test-threads=1

      - name: Check Rust Formatting
        if: matrix.os == 'ubuntu-latest'
        run: cargo fmt --check

      - name: Run Clippy
        if: matrix.os == 'ubuntu-latest'
        run: cargo clippy -- -D warnings

  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy


      - name: Install Dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 30
          command: |
            if [[ "${{ runner.os }}" == "Windows" ]] && [[ -d ".venv" ]]; then
              echo "Removing existing .venv directory on Windows"
              rm -rf .venv
            fi
            uv sync --all-packages --all-groups --all-extras
            uv pip install maturin
            uv run maturin develop --release --features extension-module
          shell: bash

      - name: Run Rust Checks
        run: |
          cargo fmt --check
          cargo clippy -- -D warnings

      - name: Install prek
        run: |
          # Install prek using uv (recommended method)
          uv tool install prek
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Load Cached Prek Dependencies
        id: cached-prek-dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/prek/
          key: prek|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Execute Prek
        run: prek run --show-diff-on-failure --color=always --all-files

  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Python
        uses: actions/setup-python@v6
        id: setup-python
        with:
          python-version: "3.13"

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Cache Python Dependencies
        id: python-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: python-dependencies-ubuntu-latest-3.10-${{ hashFiles('uv.lock') }}
          restore-keys: |
            python-dependencies-ubuntu-latest-3.10-

      - name: Install Dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 30
          command: |
            uv sync --all-packages --all-groups --all-extras
            uv pip install maturin
            uv run maturin develop --release --features extension-module
          shell: bash

      - name: Install System Dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 30
          command: |
            sudo apt-get update
            sudo apt-get install -y tesseract-ocr tesseract-ocr-deu pandoc libreoffice
            echo "Verifying installations..."
            tesseract --version
            pandoc --version
            soffice --version
          shell: bash

      - name: Install SpaCy Model for Testing
        run: |
          uv pip install "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl"

      - name: Cache HuggingFace Models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: huggingface-models-vision-tables-v1-${{ runner.os }}
          restore-keys: |
            huggingface-models-vision-tables-v1-

      - name: Download Vision-Tables Models if Not Cached
        env:
          HF_HOME: ~/.cache/huggingface
          TRANSFORMERS_CACHE: ~/.cache/huggingface
        run: |
          if [ ! -d ~/.cache/huggingface ] || [ -z "$(ls -A ~/.cache/huggingface 2>/dev/null)" ]; then
            echo "Cache miss - downloading vision-tables models..."
            uv run python scripts/download_vision_tables_models.py
          else
            echo "Using cached vision-tables models"
          fi

      - name: Run Tests with Coverage
        uses: nick-fields/retry@v3
        env:
          HF_HOME: ~/.cache/huggingface
          TRANSFORMERS_CACHE: ~/.cache/huggingface
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_wait_seconds: 10
          command: |
            uv run coverage erase
            uv run pytest -s -vvv --cov=kreuzberg --cov-report=lcov:coverage.lcov --cov-report=term --cov-config=pyproject.toml --reruns 2 --reruns-delay 1 --ignore=tests/benchmarks/
            uv run coverage report --precision=2
          shell: bash

      - name: Upload Coverage to DeepSource
        if: always()
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: |
          # Install DeepSource CLI
          curl -fsSL https://deepsource.io/cli | sh
          # Upload coverage report
          ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.lcov

      - name: Upload Coverage Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.sha }}
          path: |
            coverage.lcov
            .coverage
          retention-days: 7

  python-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.10", "3.11", "3.12", "3.13"]
        test-category:
          - name: "core"
            path: "tests/core,tests/utils"
            system-deps: false
            timeout: 20
          - name: "extractors"
            path: "tests/extractors"
            system-deps: true
            timeout: 25
          - name: "integration"
            path: "tests/integration,tests/api"
            system-deps: true
            timeout: 30
          - name: "features"
            path: "tests/features,tests/interfaces,tests/mcp,tests/multiprocessing,tests/ocr"
            system-deps: true
            timeout: 25
          - name: "comparative-benchmarks"
            path: "comparative-benchmarks/tests"
            system-deps: false
            timeout: 15
    timeout-minutes: ${{ matrix.test-category.timeout }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Python
        uses: actions/setup-python@v6
        id: setup-python
        with:
          python-version: ${{ matrix.python }}

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Cache Python Dependencies
        id: python-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: python-dependencies-${{ matrix.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            python-dependencies-${{ matrix.os }}-${{ matrix.python }}-

      - name: Install Dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 30
          command: |
            if [[ "${{ runner.os }}" == "Windows" ]] && [[ -d ".venv" ]]; then
              echo "Removing existing .venv directory on Windows"
              rm -rf .venv
            fi
            uv sync --all-packages --all-groups --all-extras
            uv pip install maturin
            uv run maturin develop --release --features extension-module
          shell: bash

      - name: Cache Test Artifacts
        uses: actions/cache@v4
        with:
          path: .pytest_cache/
          key: pytest-cache-${{ matrix.os }}-${{ matrix.python }}

      - name: Cache and Install Homebrew (macOS)
        if: runner.os == 'macOS'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_wait_seconds: 30
          command: |
            # Using the underlying homebrew commands instead of the action
            brew update || true
            brew install tesseract tesseract-lang pandoc || brew upgrade tesseract tesseract-lang pandoc || true
            brew install --cask libreoffice || brew upgrade --cask libreoffice || true
            brew list tesseract tesseract-lang pandoc
            echo "Verifying LibreOffice installation..."
            soffice --version || echo "Warning: soffice not found in PATH"
          shell: bash

      - name: Cache and Install APT Packages (Linux)
        if: runner.os == 'Linux'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 30
          command: |
            sudo apt-get update
            sudo apt-get install -y tesseract-ocr tesseract-ocr-deu pandoc libreoffice
            echo "Verifying installations..."
            tesseract --version
            pandoc --version
            soffice --version
          shell: bash

      - name: Install System Dependencies (Windows)
        if: runner.os == 'Windows'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_wait_seconds: 30
          command: |
            choco install -y tesseract pandoc libreoffice --no-progress
            Write-Output "C:\Program Files\Tesseract-OCR" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            Write-Output "C:\Program Files\Pandoc" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            Write-Output "C:\Program Files\LibreOffice\program" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            $env:PATH = "C:\Program Files\Tesseract-OCR;C:\Program Files\Pandoc;C:\Program Files\LibreOffice\program;" + $env:PATH

            # Install python-magic-bin for Windows
            pip install python-magic-bin

            # Download German language pack for Tesseract
            $tessDataDir = "C:\Program Files\Tesseract-OCR\tessdata"
            if (-not (Test-Path $tessDataDir)) {
                New-Item -ItemType Directory -Path $tessDataDir -Force
            }
            Invoke-WebRequest -Uri "https://github.com/tesseract-ocr/tessdata/raw/main/deu.traineddata" -OutFile "$tessDataDir\deu.traineddata"

            tesseract --version
            tesseract --list-langs
            pandoc --version
            soffice --version
          shell: pwsh

      - name: Install SpaCy Model for Testing
        if: matrix.test-category.system-deps
        run: |
          uv pip install "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl"

      - name: Cache HuggingFace Models
        if: contains(matrix.test-category.path, 'gmft')
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: huggingface-models-gmft-v1-${{ runner.os }}
          restore-keys: |
            huggingface-models-gmft-v1-

      - name: Download GMFT Models if Not Cached
        if: contains(matrix.test-category.path, 'gmft')
        env:
          TRANSFORMERS_CACHE: ~/.cache/huggingface
        run: |
          if [ ! -d ~/.cache/huggingface ] || [ -z "$(ls -A ~/.cache/huggingface 2>/dev/null)" ]; then
            echo "Cache miss - downloading GMFT models..."
            uv run python scripts/download_gmft_models.py
          else
            echo "Using cached GMFT models"
          fi

      - name: Run Tests - ${{ matrix.test-category.name }}
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 2
          retry_wait_seconds: 5
          command: |
            # Skip comparative-benchmarks/tests on Windows
            if [[ "${{ runner.os }}" == "Windows" ]] && [[ "${{ matrix.test-category.name }}" == "comparative-benchmarks" ]]; then
              echo "Skipping comparative-benchmarks/tests on Windows"
              exit 0
            fi
            # Run tests from specified paths, explicitly excluding benchmarks
            uv run pytest $(echo "${{ matrix.test-category.path }}" | tr ',' ' ') -v --reruns 1 --reruns-delay 1 --ignore=tests/benchmarks/
          shell: bash
