name: Docker E2E Tests

on:
  pull_request:
    paths:
      - '.docker/**'
      - 'kreuzberg/**'
      - 'pyproject.toml'
      - 'tests/e2e/**'
      - '.github/workflows/docker-e2e-tests.yml'
  workflow_dispatch:
  workflow_call:  # Allow this workflow to be called by other workflows

jobs:
  test-docker-images:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install asyncio  # For comprehensive tests

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc tesseract-ocr jq bc

      - name: Free up disk space
        run: |
          # Show initial disk usage
          echo "Initial disk usage:"
          df -h

          # Remove unnecessary packages to free up space for Docker builds
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

          # Clean apt cache
          sudo apt-get clean
          sudo apt-get autoremove -y

          # Clean Docker
          docker system prune -af --volumes

          # Remove swap
          sudo swapoff -a
          sudo rm -f /swapfile

          # Show available space after cleanup
          echo "Available disk space after cleanup:"
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Configure Docker
        run: |
          # Increase Docker daemon limits
          sudo tee /etc/docker/daemon.json > /dev/null <<EOF
          {
            "max-concurrent-downloads": 10,
            "max-concurrent-uploads": 10,
            "storage-driver": "overlay2"
          }
          EOF

          sudo systemctl restart docker
          docker info

      - name: Build Docker images
        run: |
          # Use the enhanced build script
          chmod +x tests/e2e/run_docker_tests.sh

          # Build images with logging
          export DOCKER_BUILDKIT=1
          export BUILDKIT_PROGRESS=plain

          # Build all test images sequentially for reliability
          echo "Building Docker images for E2E tests..."

          echo "Building core image..."
          docker build -f .docker/Dockerfile \
            --build-arg EXTRAS="" \
            -t kreuzberg:core \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --load \
            .

          echo "Building easyocr image..."
          docker build -f .docker/Dockerfile \
            --build-arg EXTRAS="easyocr" \
            -t kreuzberg:easyocr \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --load \
            .

          echo "Building paddle image..."
          docker build -f .docker/Dockerfile \
            --build-arg EXTRAS="paddleocr" \
            -t kreuzberg:paddle \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --load \
            .

          echo "Building gmft image..."
          docker build -f .docker/Dockerfile \
            --build-arg EXTRAS="gmft" \
            -t kreuzberg:gmft \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --load \
            .

          # List built images
          echo "Built images:"
          docker images --format "table {{.Repository}}:{{.Tag}}\t{{.Size}}" | grep kreuzberg || true

      - name: Run E2E tests
        run: |
          # Create log directory
          mkdir -p tests/e2e/logs

          echo "Running E2E test suite..."
          python3 tests/e2e/docker_images_test.py

      - name: Generate test report
        if: always()
        run: |
          # Generate summary report
          if [ -f "tests/e2e/test_report.json" ]; then
            echo "## Test Report Summary" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
            jq '.summary' tests/e2e/test_report.json >> $GITHUB_STEP_SUMMARY || echo "No summary available" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          fi

          # List any failed containers
          echo "## Docker Containers Status" >> $GITHUB_STEP_SUMMARY
          docker ps -a --filter "name=kreuzberg-test" --format "table {{.Names}}\t{{.Status}}" >> $GITHUB_STEP_SUMMARY || true

      - name: Collect Docker logs on failure
        if: failure()
        run: |
          # Collect logs from any remaining test containers
          mkdir -p tests/e2e/docker-logs

          for container in $(docker ps -a --filter "name=kreuzberg-test" --format "{{.Names}}"); do
            docker logs "$container" > "tests/e2e/docker-logs/${container}.log" 2>&1 || true
          done

          # Save Docker daemon info
          docker info > tests/e2e/docker-logs/docker-info.txt 2>&1 || true
          docker version > tests/e2e/docker-logs/docker-version.txt 2>&1 || true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-e2e-test-results
          path: |
            tests/e2e/logs/
            tests/e2e/*.log
            tests/e2e/*.json
            tests/e2e/docker-logs/
          retention-days: 7

      - name: Clean up Docker resources
        if: always()
        run: |
          # Stop and remove test containers
          docker ps -aq --filter "name=kreuzberg-test" | xargs -r docker rm -f || true

          # Remove test images
          docker rmi kreuzberg:core kreuzberg:easyocr kreuzberg:paddle kreuzberg:gmft || true

          # Clean up Docker system
          docker system prune -af --volumes || true

          # Show final disk usage
          echo "Final disk usage:"
          df -h
